line.bot:
  channel-token: '${LINE_BOT_TOKEN}'
  channel-secret: '${LINE_BOT_SECRET}'
  handler.path: ${LINE_WEBHOOK}

spring:
  datasourse:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DATABASE_IP_PORT};databaseName=${DATABASE_NAME};sslProtocol=TLS;Encrypt=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
jpa:
  show-aql: true
  hibernate.ddl-auto: update
  properties:
    hibernate:
      format_sql: true
#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    port: ${RABBITMQ_PORT}
#  activemq:
#    user: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}