spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DATABASE_IP_PORT};databaseName=${DATABASE_NAME};sslProtocol=TLS;Encrypt=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-aql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
  activemq:
    user: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  sql:
    init:
      mode: always
