apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-sender
  labels:
    app: message-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-sender
  template:
    metadata:
      labels:
        app: message-sender
    spec:
      containers:
      - name: message-sender
        image: tairitsu86/graduation-project_im-ui-system_message-sender:latest
        resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: LINE_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: message-sender-secret
              key: line-bot-token
        - name: LINE_BOT_SECRET
          valueFrom:
            secretKeyRef:
              name: message-sender-secret
              key: line-bot-secret
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: message-sender-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: message-sender-secret
              key: rabbitmq-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: message-sender-configmap
              key: rabbitmq-ip
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: message-sender-configmap
              key: rabbitmq-port
        - name: LOGIN_TRACKER_URL
          valueFrom:
            configMapKeyRef:
              name: message-sender-configmap
              key: login-tracker-url
---
apiVersion: v1
kind: Service
metadata:
  name: message-sender-service
spec:
  selector:
    app: message-sender
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8080
      nodePort: 30003


