apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: login-system
  name: user-database
  labels:
    app: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
      - name: user-database
        image: tairitsu86/graduation-project_login-system_user-database:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: user-database-username
          valueFrom: 
            secertKeyRef:
              name: user-database-secret
              key: user-database-username
        - name: user-database-password
          valueFrom: 
            secertKeyRef:
              name: user-database-secret
              key: user-database-password 
        - name: user-database-ip-port
          valueFrom:
            configMapKeyRef:
              name: user-database-configMap
              key: user-database-ip-port
        - name: user-database-databaseName
          valueFrom:
            configMapKeyRef:
              name: user-database-configMap
              key: user-database-databaseName
---
apiVersion: v1
kind: Service
metadata:
  namespace: login-system
  name: user-database-service
spec:
  selector:
    app: user-database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


