apiVersion: v1
kind: Deployment
metadata:
  name: user-database
  labels:
    app: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
      - name: user-database
        image: REPOSITORY/IMAGE:TAG
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: USER_DATABASE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: user-database-secret
              key: user-database-username
        - name: USER_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: user-database-secret
              key: user-database-password 
        - name: USER_DATABASE_IP_PORT
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: user-database-ip-port
        - name: USER_DATABASE_DATABASENAME
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: user-database-databaseName
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-service
spec:
  selector:
    app: user-database
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000


