apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-database
  labels:
    app: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-database
  template:
    metadata:
      labels:
        app: user-database
    spec:
      containers:
      - name: user-database
        image: tairitsu86/graduation-project_login-system_user-database:latest
        resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: user-database-secret
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: user-database-secret
              key: database-password
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-database-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-database-secret
              key: rabbitmq-password
        - name: DATABASE_IP_PORT
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: database-ip-port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: database-name
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: rabbitmq-ip
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: user-database-configmap
              key: rabbitmq-port
---
apiVersion: v1
kind: Service
metadata:
  name: user-database-service
spec:
  selector:
    app: user-database
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
      nodePort: 30000


