name: IM-UI-System Message-Sender Test

on:
  push:
    branches: [ "develop-IM-UI-system-message-sender" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: "graduation-project"
      SUB_SYSTEM_NAME: "im-ui-system"
      SERVICE_NAME: "message-sender"
      LINE_BOT_TOKEN: ${{ secrets.LINE_BOT_TOKEN }}
      LINE_BOT_SECRET: ${{ secrets.LINE_BOT_SECRET }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      LOGIN_TRACKER_URL: ${{ secrets.LOGIN_TRACKER_URL }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Test with Maven
      run: |
        cd $SERVICE_NAME
        mvn -B test --file pom.xml
