name: IM-UI-System Login-Tracker Test

on:
  push:
    branches: [ "develop-IM-UI-system-login-tracker" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: "graduation-project"
      SUB_SYSTEM_NAME: "im-ui-system"
      SERVICE_NAME: "login-tracker"
      DATABASE_IP_PORT: ${{ secrets.DATABASE_IP_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Test with Maven
      run: |
        cd $SERVICE_NAME
        mvn -B test --file pom.xml
