name: IM-UI-System Login-Tracker Docker build&push

on:
  push:
    branches: [ "release-IM-UI-system-login-tracker" ]

defaults:
  run:
    working-directory: ./login-tracker/

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_IP_PORT: ${{ secrets.DATABASE_IP_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tairitsu86/graduation-project_im-ui-system_login-tracker
        dockerfile: Dockerfile
        always_pull: true
        tags: latest
