name: IM-UI-System Message-Sender Docker build&push

on:
  push:
    branches: [ "release-IM-UI-system-message-sender" ]

defaults:
  run:
    working-directory: ./message-sender/

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      LINE_BOT_TOKEN: ${{ secrets.LINE_BOT_TOKEN }}
      LINE_BOT_SECRET: ${{ secrets.LINE_BOT_SECRET }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Test with Maven
      run: mvn -B test --file pom.xml
      
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      


    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
      run: |
        ls 
        ls -la target
        docker build -t graduation-project_im-ui-system_message-sender:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag graduation-project_im-ui-system_message-sender tairitsu86/graduation-project_im-ui-system_message-sender
        docker push tairitsu86/graduation-project_im-ui-system_message-sender:latest
