apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-console
  labels:
    app: test-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-console
  template:
    metadata:
      labels:
        app: test-console
    spec:
      containers:
      - name: test-console
        image: tairitsu86/graduation-project_im-ig-system_test-console:latest
        resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-console-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-console-secret
              key: rabbitmq-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: test-console-configmap
              key: rabbitmq-ip
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: test-console-configmap
              key: rabbitmq-port
---
apiVersion: v1
kind: Service
metadata:
  name: test-console-service
spec:
  selector:
    app: test-console
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8080
      nodePort: 30011


